version: '3'

services:
  sylbot:
    image: sylbot:latest
    container_name: sylbot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
      - "443:443"
    restart: unless-stopped